<a href="https://colab.research.google.com/github/ashusharma2002/Ey_Training_AI_ML_Assignments/blob/root/Day1_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#create 3*3 array random floats between 0 and 1.
#print its shape, dtype, and the value of row1 and col2.

import numpy as np
arr = np.random.rand(3, 3)

# Print array
print("Array:",arr)
print("\nShape:", arr.shape)
print("Data Type:", arr.dtype)
print("\nRow 1:")
print(arr[0])
print("\nColumn 2:")
print(arr[:, 1])


Array: [[0.3052479  0.95152199 0.92972453]
 [0.43610682 0.64846268 0.33926828]
 [0.67850823 0.90869101 0.66007065]]

Shape: (3, 3)
Data Type: float64

Row 1:
[0.3052479  0.95152199 0.92972453]

Column 2:
[0.95152199 0.64846268 0.90869101]


In [ ]:
#how many unique values does the embarked column has?
#what is most common passanger class (pclass)?
import pandas as pd

# Load dataset
df = pd.read_excel("titanic_dataset.xlsx")

# Number of unique values in embarked
print("Unique values in embarked:", df["embarked"].nunique())

# Most common passenger class
print("\nPassenger class counts:")
print(df["pclass"].value_counts())

print("\nMost common passenger class:", df["pclass"].mode()[0])

Unique values in embarked: 3

Passenger class counts:
pclass
3    491
1    216
2    184
Name: count, dtype: int64

Most common passenger class: 3


In [5]:
#using group by find
#Average fare paid by passengers from each embarkation port
#Number of survivors per class sorted from highest to lowest

avg_fare = df.groupby("embarked")["fare"].mean()
print("Average Fare by Embarkation Port:")
print(avg_fare)

# 2. Number of survivors per class sorted from highest to lowest
survivors_per_class = df.groupby("pclass")["survived"].sum().sort_values(ascending=False)

print("\nNumber of Survivors per Class:")
print(survivors_per_class)

Average Fare by Embarkation Port:
embarked
C    59.954144
Q    13.276030
S    27.079812
Name: fare, dtype: float64

Number of Survivors per Class:
pclass
1    136
3    119
2     87
Name: survived, dtype: int64
